package uz.pdp;

public interface Constants {

    String AGENT = "1. AGENT";
    String MERCHANT = "2. MERCHANT";
    String AGENT_MERCHANT = "3. AGENT_MERCHANT";
    String GATEWAY = "4. GATEWAY";
    String GATEWAY_MERCHANT = "5. GATEWAY_MERCHANT";
    String CHECK_TRANSACTION = "6. CHECK_TRANSACTION";
    String PAY_TRANSACTION = "7. PAY_TRANSACTION";
    String LIST_TRANSACTION = "8. LIST_TRANSACTION";


    String ADD_AGENT = "1. ADD_AGENT";
    String LIST_AGENT = "2. LIST_AGENT";
    String DELETE_AGENT = "3. DELETE_AGENT";

    String ADD_MERCHANT = "1. ADD_MERCHANT";
    String LIST_MERCHANT = "2. LIST_MERCHANT";
    String DELETE_MERCHANT = "3. DELETE_MERCHANT";

    String ADD_AGENT_MERCHANT = "1. ADD_AGENT_MERCHANT";
    String LIST_AGENT_MERCHANT = "2. LIST_AGENT_MERCHANT";
    String DELETE_AGENT_MERCHANT= "3. DELETE_AGENT_MERCHANT";

    String ADD_GATEWAY = "1. ADD_GATEWAY";
    String LIST_GATEWAY = "2. LIST_GATEWAY";
    String DELETE_GATEWAY = "3. DELETE_GATEWAY";

    String ADD_GATEWAY_MERCHANT = "1. ADD_GATEWAY_MERCHANT";
    String LIST_GATEWAY_MERCHANT = "2. LIST_GATEWAY_MERCHANT";
    String DELETE_GATEWAY_MERCHANT = "3. DELETE_GATEWAY_MERCHANT";
}
